name: Test, Build & Patch Release for Commits
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Run Unit tests.
        run: go test ./... -coverprofile=coverage.txt
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Build
        run: go build

  patch-release:
    if: github.event_name != 'pull_request'
    name: Release
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get next patch version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Update readme
        run: sed -i "s/v[0-9]\.[0-9]\.[0-9]/${{ steps.semvers.outputs.v_patch }}/g" README.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Insert new release tag'
          tag: -a ${{ steps.semvers.outputs.v_patch }} -m "${{ steps.semvers.outputs.v_patch }}"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semvers.outputs.v_patch }}
          generate_release_notes: true