name: Test and Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Run Unit tests.
        run: go test ./... -coverprofile=coverage.txt

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Build
        run: go build