name: Tidy up closed issue
on:
  issues:
    types:
      - closed

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: WIP