name: Copy labels
on:
  pull_request:
    types: [opened]

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}