name: Patch Release
on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Get next patch version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Update readme
        runs: |
          sed -i "" "s/v[0-9]\.[0-9]\.[0-9]/${{ steps.semvers.outputs.v_patch }}/g" README.md
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Insert new release tag'
          default_author: github_actions
          tag: -a ${{ steps.semvers.outputs.v_patch }} -m "${{ steps.semvers.outputs.v_patch }}"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semvers.outputs.v_patch }}
          generate_release_notes: true
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.19
        compress_assets: OFF